spring:
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/skill-note-test?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: tiger
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 重启生成表的方式 基础上更新，create：删除重建
    ddl-auto: update

## 文件上传路径
upload:
  path: /Users/wanbo/Pictures/gdImg
  save:
    prefix: gdImg

img:
  server: http://localhost/



#开发环境配置
server:
  #端口
  port: 7072